name = "Maple"
uuid = "90d5db4a-9bb6-11e8-1220-8362fcebe760"
authors = ["Cruor <cruoratmc@gmail.com>", "Vexatos <Stuarzt@gmx.de>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
