# Metadata enums and default <meta> dict

const intro_types = String[
    "Respawn",
    "WalkInRight",
    "WalkInLeft",
    "Jump",
    "WakeUp",
    "Fall",
    "TempleMirrorVoid",
    "None"
]

const color_grades = String[
    "oldsite",
    "reflection"
]

const inventories = String[
    "Default",
    "CH6End",
    "Core",
    "OldSite",
    "Prologue",
    "TheSummit"
]

const mountain_time = String[
    "Night",
    "Dawn",
    "Morning"
]

const core_modes = String[
    "None",
    "Cold",
    "Hot"
]

const default_meta = Dict{String, Any}(
    #"Name" => "", # Better to let Everest decide
    #"SID" => "", # Better to let Everest decide
    "Icon" => "",

    "Interlude" => false,
    "CompleteScreenName" => "",

    #"CassetteCheckpointIndex" => 0, # Better to let Everest decide

    #"TitleBaseColor" => "", # Somewhat useless, don't expose
    #"TitleAccentColor" => "", # Somewhat useless, don't expose
    #"TitleTextColor" => "", # Somewhat useless, don't expose

    "IntroType" => "WakeUp",

    "Dreaming" => false,

    "ColorGrade" => "",

    #"Wipe" => "", # Not actually supported

    "DarknessAlpha" => 0.05,
    "BloomBase" => 0.0,
    "BloomStrength" => 1.0,

    #"Jumpthru" => "", # Done on a per entity basis in editor, not useful for us

    "CoreMode" => "",

    "CassetteNoteColor" => "",
    "CassetteSong" => "",

    #"FixRotateSpinnerAngles" => true # Now fixed in Celeste, Everest no longer has this exposed
)

const default_mode = Dict{String, Any}(
    "IgnoreLevelAudioLayerData" => false,
    "Inventory" => "Default",
    #"Path" => "", # We have allready loaded the file, this can always be null
    #"PoemID" => "", # Autogenerated by Everest

    "StartLevel" => "",
    "HeartIsEnd" => false
)